export default {
  uid: '',
  name: '',
  plant_type: '',
  price_per_unit: '',
  currency_code: 'EUR',
  quantity: '',
  quantity_unit: '',
  expiration_date: '',
  farm_id: '',
  notes: '',
  is_expense: '',
  produced_by: '',
  type: '',
  chemical_type: '',
}
