export default {
  uid: '',
  description: '',
  due_date: '',
  priority: '',
  type: '',
  source_area_id: '',
  dest_area_id: '',
  quantity: '',
  type: '',
  units: '',
  asset_id: '',
  category: '',
  title: '',
  fertilizer: '',
  pesticide: '',
}
