linters:
  fast: false
  disable:
    - errcheck
  enable:
    - deadcode
    #- errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    #- cyclop
    - depguard
    - dogsled
    #- dupl
    - durationcheck
    - errname
    #- errorlint
    - exhaustive
    #- exhaustivestruct
    - exportloopref
    #- forbidigo
    #- forcetypeassert
    #- funlen
    - gci
    #- gochecknoglobals
    #- gocognit
    #- goconst
    #- gocritic
    #- gocyclo
    #- godot
    #- godox
    #- goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    #- gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    #- ifshort
    - importas
    #- ireturn
    #- lll
    - makezero
    - misspell
    - nakedret
    #- nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    #- paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    #- rowserrcheck
    #- sqlclosecheck
    - stylecheck
    #- tagliatelle
    - tenv
    #- testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    #- varnamelen
    - wastedassign
    - whitespace
    #- wrapcheck
    #- wsl

run:
  tests: true
