-- FARM --

CREATE TABLE IF NOT EXISTS "FARM_EVENT" (
    "ID" INTEGER PRIMARY KEY,
    "FARM_UID" BLOB,
    "VERSION" INTEGER,
    "CREATED_DATE" TEXT,
    "EVENT" JSON
);

CREATE INDEX IF NOT EXISTS "FARM_EVENT_FARM_UID_INDEX" ON "FARM_EVENT" ("FARM_UID");

CREATE TABLE IF NOT EXISTS "FARM_READ" (
    "UID" BLOB PRIMARY KEY,
    "NAME" TEXT,
    "LATITUDE" TEXT,
    "LONGITUDE" TEXT,
    "TYPE" TEXT,
    "COUNTRY_CODE" TEXT,
    "CITY_CODE" TEXT,
    "IS_ACTIVE" INTEGER,
    "CREATED_DATE" TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS "FARM_READ_UID_UNIQUE_INDEX" ON "FARM_READ" ("UID");

-- AREA --

CREATE TABLE IF NOT EXISTS "AREA_EVENT" (
    "ID" INTEGER PRIMARY KEY,
    "AREA_UID" BLOB,
    "VERSION" INTEGER,
    "CREATED_DATE" TEXT,
    "EVENT" JSON
);

CREATE INDEX IF NOT EXISTS "FARM_EVENT_AREA_UID_INDEX" ON "AREA_EVENT" ("AREA_UID");

CREATE TABLE IF NOT EXISTS "AREA_READ" (
    "UID" BLOB PRIMARY KEY,
    "NAME" TEXT,
    "SIZE_UNIT" TEXT,
    "SIZE" REAL,
    "TYPE" TEXT,
    "LOCATION" TEXT,
    "PHOTO_FILENAME" TEXT,
    "PHOTO_MIMETYPE" TEXT,
    "PHOTO_SIZE" INTEGER,
    "PHOTO_WIDTH" INTEGER,
    "PHOTO_HEIGHT" INTEGER,
    "CREATED_DATE" TEXT,
    "RESERVOIR_UID" BLOB,
    "RESERVOIR_NAME" TEXT,
    "FARM_UID" BLOB,
    "FARM_NAME" TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS "AREA_READ_UID_UNIQUE_INDEX" ON "AREA_READ" ("UID");
CREATE INDEX IF NOT EXISTS "AREA_READ_RESERVOIR_UID_INDEX" ON "AREA_READ" ("RESERVOIR_UID");
CREATE INDEX IF NOT EXISTS "AREA_READ_FARM_UID_INDEX" ON "AREA_READ" ("FARM_UID");

CREATE TABLE IF NOT EXISTS "AREA_READ_NOTES" (
    "UID" BLOB PRIMARY KEY,
    "AREA_UID" BLOB,
    "CONTENT" TEXT,
    "CREATED_DATE" TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS "AREA_READ_NOTES_UID_UNIQUE_INDEX" ON "AREA_READ_NOTES" ("UID");
CREATE INDEX IF NOT EXISTS "AREA_READ_NOTES_AREA_UID_INDEX" ON "AREA_READ_NOTES" ("AREA_UID");

-- RESERVOIR --

CREATE TABLE IF NOT EXISTS "RESERVOIR_EVENT" (
    "ID" INTEGER PRIMARY KEY,
    "RESERVOIR_UID" BLOB,
    "VERSION" INTEGER,
    "CREATED_DATE" TEXT,
    "EVENT" BLOB
);

CREATE INDEX IF NOT EXISTS "RESERVOIR_EVENT_RESERVOIR_UID_INDEX" ON "RESERVOIR_EVENT" ("RESERVOIR_UID");

CREATE TABLE IF NOT EXISTS "RESERVOIR_READ" (
    "UID" BLOB PRIMARY KEY,
    "NAME" TEXT,
    "WATERSOURCE_TYPE" TEXT,
    "WATERSOURCE_CAPACITY" REAL,
    "FARM_UID" BLOB,
    "FARM_NAME" TEXT,
    "CREATED_DATE" TEXT
);

CREATE INDEX IF NOT EXISTS "RESERVOIR_READ_UID_UNIQUE_INDEX" ON "RESERVOIR_READ" ("UID");

CREATE TABLE IF NOT EXISTS "RESERVOIR_READ_NOTES" (
    "UID" BLOB PRIMARY KEY,
    "RESERVOIR_UID" BLOB,
    "CONTENT" TEXT,
    "CREATED_DATE" TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS "RESERVOIR_READ_NOTES_UID_UNIQUE_INDEX" ON "RESERVOIR_READ_NOTES" ("UID");
CREATE INDEX IF NOT EXISTS "RESERVOIR_READ_NOTES_RESERVOIR_UID_INDEX" ON "RESERVOIR_READ_NOTES" ("RESERVOIR_UID");

-- MATERIAL --

CREATE TABLE IF NOT EXISTS "MATERIAL_EVENT" (
    "ID" INTEGER PRIMARY KEY,
    "MATERIAL_UID" BLOB,
    "VERSION" INTEGER,
    "CREATED_DATE" TEXT,
    "EVENT" BLOB
);

CREATE INDEX IF NOT EXISTS "MATERIAL_EVENT_MATERIAL_UID_INDEX" ON "MATERIAL_EVENT" ("MATERIAL_UID");

CREATE TABLE IF NOT EXISTS "MATERIAL_READ" (
    "UID" BLOB PRIMARY KEY,
    "NAME" TEXT,
    "PRICE_PER_UNIT" TEXT,
    "CURRENCY_CODE" TEXT,
    "TYPE" TEXT,
    "TYPE_DATA" TEXT,
    "QUANTITY" REAL,
    "QUANTITY_UNIT" TEXT,
    "EXPIRATION_DATE" TEXT,
    "NOTES" TEXT,
    "PRODUCED_BY" TEXT,
    "CREATED_DATE" TEXT
);

CREATE INDEX IF NOT EXISTS "MATERIAL_READ_UID_UNIQUE_INDEX" ON "MATERIAL_READ" ("UID");