-- FARM --

CREATE TABLE IF NOT EXISTS `FARM_EVENT` (
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `FARM_UID` BINARY(16),
    `VERSION` INT,
    `CREATED_DATE` DATETIME,
    `EVENT` JSON
) ENGINE=InnoDB;

CREATE INDEX `FARM_EVENT_FARM_UID_INDEX` ON `FARM_EVENT` (`FARM_UID`);

CREATE TABLE IF NOT EXISTS `FARM_READ` (
    `UID` BINARY(16) PRIMARY KEY,
    `NAME` VARCHAR(255),
    `LATITUDE` VARCHAR(255),
    `LONGITUDE` VARCHAR(255),
    `TYPE` VARCHAR(255),
    `COUNTRY_CODE` VARCHAR(255),
    `CITY_CODE` VARCHAR(255),
    `IS_ACTIVE` INT,
    `CREATED_DATE` DATETIME
) ENGINE=InnoDB;

CREATE UNIQUE INDEX `FARM_READ_UID_UNIQUE_INDEX` ON `FARM_READ` (`UID`);

-- RESERVOIR --

CREATE TABLE IF NOT EXISTS `RESERVOIR_EVENT` (
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `RESERVOIR_UID` BINARY(16),
    `VERSION` INT,
    `CREATED_DATE` DATETIME,
    `EVENT` JSON
) ENGINE=InnoDB;

CREATE INDEX `RESERVOIR_EVENT_RESERVOIR_UID_INDEX` ON `RESERVOIR_EVENT` (`RESERVOIR_UID`);

CREATE TABLE IF NOT EXISTS `RESERVOIR_READ` (
    `UID` BINARY(16) PRIMARY KEY,
    `NAME` VARCHAR(255),
    `WATERSOURCE_TYPE` VARCHAR(255),
    `WATERSOURCE_CAPACITY` FLOAT,
    `FARM_UID` BINARY(16),
    `FARM_NAME` VARCHAR(255),
    `CREATED_DATE` DATETIME
) ENGINE=InnoDB;

CREATE INDEX `RESERVOIR_READ_UID_UNIQUE_INDEX` ON `RESERVOIR_READ` (`UID`);

CREATE TABLE IF NOT EXISTS `RESERVOIR_READ_NOTES` (
    `UID` BINARY(16) PRIMARY KEY,
    `RESERVOIR_UID` BINARY(16),
    `CONTENT` TEXT,
    `CREATED_DATE` DATETIME,
    FOREIGN KEY(`RESERVOIR_UID`) REFERENCES `RESERVOIR_READ`(`UID`)
) ENGINE=InnoDB;

CREATE UNIQUE INDEX `RESERVOIR_READ_NOTES_UID_UNIQUE_INDEX` ON `RESERVOIR_READ_NOTES` (`UID`);
CREATE INDEX `RESERVOIR_READ_NOTES_RESERVOIR_UID_INDEX` ON `RESERVOIR_READ_NOTES` (`RESERVOIR_UID`);

-- AREA --

CREATE TABLE IF NOT EXISTS `AREA_EVENT` (
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `AREA_UID` BINARY(16),
    `VERSION` INT,
    `CREATED_DATE` DATETIME,
    `EVENT` JSON
) ENGINE=InnoDB;

CREATE INDEX `FARM_EVENT_AREA_UID_INDEX` ON `AREA_EVENT` (`AREA_UID`);

CREATE TABLE IF NOT EXISTS `AREA_READ` (
    `UID` BINARY(16) PRIMARY KEY,
    `NAME` VARCHAR(255),
    `SIZE_UNIT` VARCHAR(255),
    `SIZE` FLOAT,
    `TYPE` VARCHAR(255),
    `LOCATION` VARCHAR(255),
    `PHOTO_FILENAME` VARCHAR(255),
    `PHOTO_MIMETYPE` VARCHAR(255),
    `PHOTO_SIZE` INT,
    `PHOTO_WIDTH` INT,
    `PHOTO_HEIGHT` INT,
    `CREATED_DATE` DATETIME,
    `RESERVOIR_UID` BINARY(16),
    `RESERVOIR_NAME` VARCHAR(255),
    `FARM_UID` BINARY(16),
    `FARM_NAME` VARCHAR(255)
) ENGINE=InnoDB;

CREATE UNIQUE INDEX `AREA_READ_UID_UNIQUE_INDEX` ON `AREA_READ` (`UID`);
CREATE INDEX `AREA_READ_RESERVOIR_UID_INDEX` ON `AREA_READ` (`RESERVOIR_UID`);
CREATE INDEX `AREA_READ_FARM_UID_INDEX` ON `AREA_READ` (`FARM_UID`);

CREATE TABLE IF NOT EXISTS `AREA_READ_NOTES` (
    `UID` BINARY(16) PRIMARY KEY,
    `AREA_UID` BINARY(16),
    `CONTENT` TEXT,
    `CREATED_DATE` DATETIME,
    FOREIGN KEY(`AREA_UID`) REFERENCES `AREA_READ`(`UID`)
) ENGINE=InnoDB;

CREATE UNIQUE INDEX `AREA_READ_NOTES_UID_UNIQUE_INDEX` ON `AREA_READ_NOTES` (`UID`);
CREATE INDEX `AREA_READ_NOTES_AREA_UID_INDEX` ON `AREA_READ_NOTES` (`AREA_UID`);
