-- FARM --

CREATE TABLE IF NOT EXISTS `FARM_EVENT` (
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `FARM_UID` BINARY(16),
    `VERSION` INT,
    `CREATED_DATE` DATETIME,
    `EVENT` JSON
) ENGINE=InnoDB;

CREATE INDEX `FARM_EVENT_FARM_UID_INDEX` ON `FARM_EVENT` (`FARM_UID`);

CREATE TABLE IF NOT EXISTS `FARM_READ` (
    `UID` BINARY(16) PRIMARY KEY,
    `NAME` VARCHAR(255),
    `LATITUDE` VARCHAR(255),
    `LONGITUDE` VARCHAR(255),
    `TYPE` VARCHAR(255),
    `COUNTRY_CODE` VARCHAR(255),
    `CITY_CODE` VARCHAR(255),
    `IS_ACTIVE` INT,
    `CREATED_DATE` DATETIME
) ENGINE=InnoDB;

CREATE UNIQUE INDEX `FARM_READ_UID_UNIQUE_INDEX` ON `FARM_READ` (`UID`);

