export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'
export const FETCH_CITIES = 'FETCH_CITIES'

export const FETCH_FARM_TYPES = 'FETCH_FARM_TYPES'
export const CREATE_FARM = 'CREATE_FARM'
export const SET_FARM = 'SET_FARM'
export const CREATE_RESERVOIR = 'CREATE_RESERVOIR'

export const CREATE_AREA = 'CREATE_AREA'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_COMPLETED_INTRO = 'USER_COMPLETED_INTRO'
